site_name: {{ cookiecutter.project_name }}
site_author: {{ cookiecutter.author_name }}
docs_dir: source

theme:
  language: en
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    features:
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - search.suggest
    - search.highlight